name: Deploy to Google Cloud Functions

on:
  push:
    branches:
      - master  # ✅ correct branch name

jobs:
  deploy:
    name: Deploy to GCF
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy Cloud Function
        run: |
          gcloud functions deploy ${{ secrets.GCP_FUNCTION_NAME }} \
            --runtime python310 \
            --trigger-topic=db-status-schedule \
            --entry-point=main \
            --source=. \
            --region=${{ secrets.GCP_REGION }} \
            --set-secrets=DATABASE_URLS=DATABASE_URLS:latest


